---
title: "Untitled"
author: "Isha Mantri"
format: 
  html: default
  pdf: default
execute: 
  echo: false
editor: visual
---

```{r}
#loading required libraries

#| include: false
#| message: false
#| warning: false

library(tidyverse)
library(knitr)
library(lubridate)

```

```{r}

#| include: false
raw_data <- read_csv("data/36831700_Isha_Mantri.csv")
processed_data <- raw_data |>
    drop_na(purchase_amount) |>    
  mutate(
signup_date = parse_date_time(signup_date, orders = c("ymd", "dmy", "mdy", "b d, Y"))) |>
  select(-notes)
   
```

```{r}
n_obs <- nrow(processed_data)
n_vars <- ncol(processed_data)
```

```{r}
#| label: tbl-summarytable
#| tbl-cap: "Summary of Average Spend and Purchases Across Customer Segmets"

processed_data |>
  group_by(segment) |>
  summarise(
    Customers = n(),
    Avg_spend  = round(mean(marketing_spend),2),
    Avg_pur = round(mean(purchase_amount),2)
  )|>
  kable()
```

```{r}

#| label: fig-marketing-distribution
#| fig-cap: "How Marketing Spend was distributed across Customer Segment"

ggplot(processed_data, aes(x=marketing_spend, fill = segment)) +
  geom_histogram(bins = 20) +
  facet_wrap(~segment) +
  labs(
    x = "Marketing Spend",
    y = "Number of Customers"
  )
```
